export const dataNet = [
  {
    id: 1,
    title: "Aknet",
    type: "Premium",
    speed: 120,
    latency: "120 мс",
    price: "15$",
    description: "Идеальный выбор для стриминга и онлайн-игр.",
  },
  {
    id: 2,
    title: "Beeline",
    type: "Family",
    speed: 150,
    latency: "140 мс",
    price: "20$",
    description: "Быстрый интернет для всей семьи.",
  },
  {
    id: 3,
    title: "Megacom",
    type: "Basic",
    speed: 100,
    latency: "110 мс",
    price: "10$",
    description: "Доступный тариф для базового использования.",
  },
  {
    id: 4,
    title: "Кыргызтелеком",
    type: "Business",
    speed: 200,
    latency: "90 мс",
    price: "25$",
    description: "Стабильный интернет для работы и бизнеса.",
  },
  {
    id: 5,
    title: "Aknet",
    type: "Premium",
    speed: 300,
    latency: "80 мс",
    price: "30$",
    description: "Максимальная скорость для профессионалов.",
  },
  {
    id: 6,
    title: "Beeline",
    type: "Basic",
    speed: 50,
    latency: "150 мс",
    price: "8$",
    description: "Экономичный тариф для начального уровня.",
  },
  {
    id: 7,
    title: "Megacom",
    type: "Gaming",
    speed: 250,
    latency: "100 мс",
    price: "22$",
    description: "Оптимальный тариф для геймеров.",
  },
  {
    id: 8,
    title: "Кыргызтелеком",
    type: "Premium",
    speed: 400,
    latency: "70 мс",
    price: "35$",
    description: "Премиальный интернет для больших домов.",
  },
  {
    id: 9,
    title: "Aknet",
    type: "Family",
    speed: 75,
    latency: "130 мс",
    price: "12$",
    description: "Надежный тариф для небольших семей.",
  },
  {
    id: 10,
    title: "Beeline",
    type: "Ultra",
    speed: 600,
    latency: "60 мс",
    price: "50$",
    description: "Идеально подходит для высоких нагрузок.",
  },
  {
    id: 11,
    title: "Megacom",
    type: "Business",
    speed: 400,
    latency: "85 мс",
    price: "28$",
    description: "Скорость и стабильность для бизнеса.",
  },
  {
    id: 12,
    title: "Кыргызтелеком",
    type: "Premium Ultra",
    speed: 1000,
    latency: "50 мс",
    price: "60$",
    description: "Безграничные возможности для больших команд.",
  },
];
