export const dataNet = [
  {
    id: 1,
    provider: "Aknet",
    type: "Premium",
    speed: "120 Mbps",
    latency: "120 мс",
    price: "15$",
    description: "Идеальный выбор для стриминга и онлайн-игр.",
  },
  {
    id: 2,
    provider: "Beeline",
    type: "Family",
    speed: "150 Mbps",
    latency: "140 мс",
    price: "20$",
    description: "Быстрый интернет для всей семьи.",
  },
  {
    id: 3,
    provider: "Megacom",
    type: "Basic",
    speed: "100 Mbps",
    latency: "110 мс",
    price: "10$",
    description: "Доступный тариф для базового использования.",
  },
  {
    id: 4,
    provider: "Кыргызтелеком",
    type: "Business",
    speed: "200 Mbps",
    latency: "90 мс",
    price: "25$",
    description: "Стабильный интернет для работы и бизнеса.",
  },
  {
    id: 5,
    provider: "Aknet",
    type: "Premium",
    speed: "300 Mbps",
    latency: "80 мс",
    price: "30$",
    description: "Максимальная скорость для профессионалов.",
  },
  {
    id: 6,
    provider: "Beeline",
    type: "Basic",
    speed: "50 Mbps",
    latency: "150 мс",
    price: "8$",
    description: "Экономичный тариф для начального уровня.",
  },
  {
    id: 7,
    provider: "Megacom",
    type: "Gaming",
    speed: "250 Mbps",
    latency: "100 мс",
    price: "22$",
    description: "Оптимальный тариф для геймеров.",
  },
  {
    id: 8,
    provider: "Кыргызтелеком",
    type: "Premium",
    speed: "400 Mbps",
    latency: "70 мс",
    price: "35$",
    description: "Премиальный интернет для больших домов.",
  },
  {
    id: 9,
    provider: "Aknet",
    type: "Family",
    speed: "75 Mbps",
    latency: "130 мс",
    price: "12$",
    description: "Надежный тариф для небольших семей.",
  },
  {
    id: 10,
    provider: "Beeline",
    type: "Ultra",
    speed: "600 Mbps",
    latency: "60 мс",
    price: "50$",
    description: "Идеально подходит для высоких нагрузок.",
  },
  {
    id: 11,
    provider: "Megacom",
    type: "Business",
    speed: "400 Mbps",
    latency: "85 мс",
    price: "28$",
    description: "Скорость и стабильность для бизнеса.",
  },
  {
    id: 12,
    provider: "Кыргызтелеком",
    type: "Premium Ultra",
    speed: "1000 Mbps",
    latency: "50 мс",
    price: "60$",
    description: "Безграничные возможности для больших команд.",
  },
];
